import json

path = r'c:\Users\wangh\Desktop\text2sql\Wang haopeng_3161130.ipynb'

with open(path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Cell 2: ResDilatedCNN
nb['cells'][2]['source'] = [
    "#Part 2: Coding - Building the Architectures\n",
    "#Your task is to fill in the missing code (marked with ### YOUR CODE HERE ###) to define the forward pass for each architecture.\n",
    "\n",
    "#1. Residual Dilated CNN\n",
    "#You must implement a CNN that uses Dilated Convolutions to capture a wide receptive field while maintaining a Residual (Skip) Connection to preserve gradient flow.\n",
    "class ResDilatedCNN(nn.Module):\n",
    "    def __init__(self):\n",
    "        super(ResDilatedCNN, self).__init__()\n",
    "        \"\"\"\n",
    "        TODO:\n",
    "        1. Define a dilated conv layer (dilation=2) that maintains 28x28 resolution.\n",
    "        2. Define a 1x1 projection conv if the input channels don't match output.\n",
    "        3. Define BatchNormalization and a final FC layer for 10 classes.\n",
    "        \"\"\"\n",
    "        ### YOUR CODE HERE ###\n",
    "        self.dilated_conv = nn.Conv2d(1, 32, kernel_size=3, dilation=2, padding=2)\n",
    "        self.projection = nn.Conv2d(1, 32, kernel_size=1)\n",
    "        self.bn = nn.BatchNorm2d(32)\n",
    "        self.relu = nn.ReLU()\n",
    "        self.pool = nn.AdaptiveAvgPool2d((1, 1))\n",
    "        self.fc = nn.Linear(32, 10)\n",
    "        ### END CODE ###\n",
    "\n",
    "    def forward(self, x):\n",
    "        \"\"\"\n",
    "        TODO: Implement the forward pass with a Residual Connection.\n",
    "        The block should perform: Activation(BN(DilatedConv(x)) + Projection(x))\n",
    "        \"\"\"\n",
    "        ### YOUR CODE HERE ###\n",
    "        residual = self.projection(x)\n",
    "        out = self.dilated_conv(x)\n",
    "        out = self.bn(out)\n",
    "        out = self.relu(out + residual)\n",
    "        out = self.pool(out)\n",
    "        out = out.view(out.size(0), -1)\n",
    "        out = self.fc(out)\n",
    "        return out\n",
    "        ### END CODE ###"
]

# Cell 3: ManualGRU
nb['cells'][3]['source'] = [
    "#2. Manual GRU (Recurrent Neural Network)MNIST images are $28 \\times 28$. We will treat each image as a sequence of 28 rows. You must manually implement the GRU Cell logic.\n",
    "class ManualGRU(nn.Module):\n",
    "    def __init__(self, input_dim=28, hidden_dim=128):\n",
    "        super(ManualGRU, self).__init__()\n",
    "        self.hidden_dim = hidden_dim\n",
    "        \"\"\"\n",
    "        TODO: Define parameters for Reset Gate (r), Update Gate (z), and Candidate (n).\n",
    "        Hint: Use nn.Linear(input_dim + hidden_dim, hidden_dim) for gates.\n",
    "        \"\"\"\n",
    "        ### YOUR CODE HERE ###\n",
    "        self.reset_gate = nn.Linear(input_dim + hidden_dim, hidden_dim)\n",
    "        self.update_gate = nn.Linear(input_dim + hidden_dim, hidden_dim)\n",
    "        self.candidate = nn.Linear(input_dim + hidden_dim, hidden_dim)\n",
    "        self.fc = nn.Linear(hidden_dim, 10)\n",
    "        ### END CODE ###\n",
    "\n",
    "    def forward(self, x):\n",
    "        # x shape: [Batch, 1, 28, 28] -> Convert to [Batch, 28, 28]\n",
    "\n",
    "        \"\"\"\n",
    "        TODO: Loop through the sequence length (L).\n",
    "        \"\"\"\n",
    "        ### YOUR CODE HERE ###\n",
    "        x = x.squeeze(1)\n",
    "        batch_size, seq_len, _ = x.size()\n",
    "        h = torch.zeros(batch_size, self.hidden_dim, device=x.device)\n",
    "\n",
    "        for t in range(seq_len):\n",
    "            x_t = x[:, t, :]\n",
    "            combined = torch.cat([x_t, h], dim=1)\n",
    "            r = torch.sigmoid(self.reset_gate(combined))\n",
    "            z = torch.sigmoid(self.update_gate(combined))\n",
    "            combined_n = torch.cat([x_t, r * h], dim=1)\n",
    "            n = torch.tanh(self.candidate(combined_n))\n",
    "            h = (1 - z) * n + z * h\n",
    "\n",
    "        out = self.fc(h)\n",
    "        return out\n",
    "        ### END CODE ###"
]

# Cell 4: GQAAttention
nb['cells'][4]['source'] = [
    "#3. Grouped Query Attention (GQA)\n",
    "#Implement the GQA mechanism, which is more efficient than standard Multi-Head Attention by sharing Keys and Values across groups of Queries.\n",
    "class GQAAttention(nn.Module):\n",
    "    def __init__(self, d_model=28, n_heads=4, n_groups=2):\n",
    "        super().__init__()\n",
    "        self.n_heads = n_heads\n",
    "        self.n_groups = n_groups\n",
    "        self.n_kv_heads = n_heads // n_groups\n",
    "        self.d_k = d_model // n_heads\n",
    "\n",
    "        \"\"\"\n",
    "        TODO: Define Linear layers for Q, K, and V.\n",
    "        Note: K and V dimensions must correspond to n_kv_heads.\n",
    "        \"\"\"\n",
    "        ### YOUR CODE HERE ###\n",
    "        self.W_q = nn.Linear(d_model, d_model)\n",
    "        self.W_k = nn.Linear(d_model, self.n_kv_heads * self.d_k)\n",
    "        self.W_v = nn.Linear(d_model, self.n_kv_heads * self.d_k)\n",
    "        self.W_o = nn.Linear(d_model, d_model)\n",
    "        self.fc = nn.Linear(d_model, 10)\n",
    "        ### END CODE ###\n",
    "\n",
    "    def forward(self, x):\n",
    "        \"\"\"\n",
    "        TODO:\n",
    "        1. Project Q, K, V and split into heads.\n",
    "        2. Expand/Repeat K and V heads to match Q heads.\n",
    "        3. Compute Scaled Dot-Product Attention and project back to D.\n",
    "        \"\"\"\n",
    "        ### YOUR CODE HERE ###\n",
    "        x = x.squeeze(1)\n",
    "        B, L, D = x.shape\n",
    "\n",
    "        q = self.W_q(x).view(B, L, self.n_heads, self.d_k).transpose(1, 2)\n",
    "        k = self.W_k(x).view(B, L, self.n_kv_heads, self.d_k).transpose(1, 2)\n",
    "        v = self.W_v(x).view(B, L, self.n_kv_heads, self.d_k).transpose(1, 2)\n",
    "\n",
    "        repeat_factor = self.n_heads // self.n_kv_heads\n",
    "        k = k.repeat_interleave(repeat_factor, dim=1)\n",
    "        v = v.repeat_interleave(repeat_factor, dim=1)\n",
    "\n",
    "        attn_scores = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(self.d_k)\n",
    "        attn_weights = F.softmax(attn_scores, dim=-1)\n",
    "        attn_output = torch.matmul(attn_weights, v)\n",
    "\n",
    "        attn_output = attn_output.transpose(1, 2).contiguous().view(B, L, D)\n",
    "        out = self.W_o(attn_output)\n",
    "        out = out.mean(dim=1)\n",
    "        out = self.fc(out)\n",
    "        return out\n",
    "        ### END CODE ###"
]

# Cell 5: train/test
nb['cells'][5]['source'] = [
    "#Training & Evaluation Pipeline\n",
    "def train(model, device, train_loader, optimizer, epoch):\n",
    "    model.train()\n",
    "    for batch_idx, (data, target) in enumerate(train_loader):\n",
    "        data, target = data.to(device), target.to(device)\n",
    "\n",
    "        \"\"\"\n",
    "        TODO:\n",
    "        1. Zero the optimizer gradients.\n",
    "        2. Forward pass.\n",
    "        3. Calculate CrossEntropy Loss.\n",
    "        4. Backward pass and optimizer step.\n",
    "        \"\"\"\n",
    "        ### YOUR CODE HERE ###\n",
    "        optimizer.zero_grad()\n",
    "        output = model(data)\n",
    "        loss = criterion(output, target)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        ### END CODE ###\n",
    "\n",
    "def test(model, device, test_loader):\n",
    "    model.eval()\n",
    "    test_loss = 0\n",
    "    correct = 0\n",
    "    with torch.no_grad():\n",
    "        for data, target in test_loader:\n",
    "            data, target = data.to(device), target.to(device)\n",
    "            \"\"\"\n",
    "            TODO: Calculate total correct predictions.\n",
    "            \"\"\"\n",
    "            ### YOUR CODE HERE ###\n",
    "            output = model(data)\n",
    "            pred = output.argmax(dim=1, keepdim=True)\n",
    "            correct += pred.eq(target.view_as(pred)).sum().item()\n",
    "            ### END CODE ###\n",
    "    print(f'\\nTest Accuracy: {100. * correct / len(test_loader.dataset):.2f}%')\n",
    "\n",
    "\n",
    "# Define models to compare\n",
    "models_to_test = {\n",
    "    \"Res-Dilated-CNN\": ResDilatedCNN().to(DEVICE),\n",
    "    \"Manual-GRU\": ManualGRU(input_dim=28, hidden_dim=128).to(DEVICE),\n",
    "    \"GQA-Transformer\": GQAAttention(d_model=28, n_heads=4, n_groups=2).to(DEVICE)\n",
    "}\n",
    "\n",
    "criterion = nn.CrossEntropyLoss()\n",
    "\n",
    "for name, model in models_to_test.items():\n",
    "    print(f\"\\n--- Evaluate Model: {name} ---\")\n",
    "    optimizer = optim.Adam(model.parameters(), lr=LR)\n",
    "\n",
    "    for epoch in range(1, EPOCHS + 1):\n",
    "        train(model, DEVICE, train_loader, optimizer, criterion, epoch)\n",
    "        acc = test(model, DEVICE, test_loader)\n",
    "        print(f'{name} Accuracy after Epoch {epoch}: {acc:.2f}%')"
]

with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=2)

print('SUCCESS: All cells updated.')



